name: Rust CI (Windows)

on:
  push:
    branches: ["*"]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build, Lint, Format & Test (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Rust toolchain (stable)
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          cache: true
          override: true

      - name: Run cargo check
        run: cargo check --all --locked --verbose
        continue-on-error: true

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
        continue-on-error: true

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        continue-on-error: true

      - name: Run cargo test
        run: cargo test --all --locked --verbose
        continue-on-error: true
